  name: Smoke Tests
  on: [push, pull_request]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - run: exit 1
    deploy:
       runs-on: ubuntu-latest
       needs: 
         - build  
       if: ${{ failure() }}
       steps:
         - name: Run if ANY of the jobs I depend on fails
           run: |
             echo "A job I'm dependent on job failed!"
             exit 1
